---
deployment:
  tasks:
    - export DEPLOYPATH=/home/nmrlkv60/avnuapistg/
    - /bin/cp -R src $DEPLOYPATH
    - /bin/cp -R migrations $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp tsconfig.json $DEPLOYPATH
    - /bin/cp .swcrc $DEPLOYPATH
    - /bin/cp .eslintrc $DEPLOYPATH
    - /bin/cp .eslintignore $DEPLOYPATH