FROM node:16-alpine as apibuild

# Install python3 into the deps of the container. For the argon bug : 2022-05-30 : Error: Error loading shared library /api/node_modules/argon2/lib/binding/napi-v3/argon2.node: Exec format error
# --virtual .builds-deps
# RUN apk --no-cache add build-base python3

## API
RUN mkdir -p /api
WORKDIR /api
COPY ./package.json .
COPY ./src .

RUN npm install

# Argon2 prebuild library seem off. We rebuild them all with this.
RUN npm rebuild

EXPOSE 8000

ENTRYPOINT ["npm"]
CMD ["run","dev"]