FROM node:16-alpine AS deps

# Install python3 into the deps of the container. For the argon bug : 2022-05-30 : Error: Error loading shared library /api/node_modules/argon2/lib/binding/napi-v3/argon2.node: Exec format error
RUN apk --no-cache add --virtual .builds-deps build-base python3

## API
WORKDIR /api
COPY ["package.json", "./"]


RUN npm install

# Argon2 prebuild library seem off. We rebuild them all with this.
RUN npm rebuild


COPY . .

EXPOSE 8000


ENTRYPOINT ["npm"]
CMD ["run","dev"]